"""empty message

Revision ID: 535fbc72ae5f
Revises: ffdc0a98111c
Create Date: 2022-11-12 16:57:49.271694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535fbc72ae5f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=2000), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=2000), nullable=False),
    sa.Column('task_detail', sa.String(length=2000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=True),
    sa.Column('taskId', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('courseId', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollmentId', sa.Integer(), nullable=True),
    sa.Column('assignmentId', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignmentId'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['enrollmentId'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresses')
    op.drop_table('enrollments')
    op.drop_table('assignments')
    op.drop_table('tasks')
    op.drop_table('courses')
    # ### end Alembic commands ###
